# Generated by Django 3.1.7 on 2021-02-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20210224_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='static/images/', width_field=100),
        ),
    ]
